// Command wraith runs the WRAI.TH fleet manager + Mission Control dashboard.
// This is the client binary — it connects to a running agent-relay server
// and manages Claude subprocesses on this machine.
//
// Usage:
//
//	wraith                     # start with wraith.yaml in cwd
//	wraith --config path.yaml  # custom config
//	wraith init                # generate wraith.yaml scaffold
//	wraith init --project foo  # with project name
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"agent-relay/internal/client"
	"agent-relay/internal/dashboard"
	"agent-relay/internal/discord"
	"agent-relay/internal/monitor"
)

var Version = "dev"

func main() {
	if len(os.Args) > 1 && os.Args[1] == "init" {
		runInit(os.Args[2:])
		return
	}

	configPath := flag.String("config", "wraith.yaml", "path to wraith config file")
	showVersion := flag.Bool("version", false, "print version and exit")
	flag.Parse()

	if *showVersion {
		fmt.Printf("wraith %s\n", Version)
		return
	}

	log.SetFlags(log.LstdFlags | log.Lshortfile)

	// --- Load config ---
	cfg, err := client.LoadConfig(*configPath)
	if err != nil {
		log.Fatalf("failed to load config: %v", err)
	}

	log.Printf("[wraith] mode=%s machine=%s relay=%s", cfg.Mode, cfg.Machine.Name, cfg.Relay.URL)

	// --- Create shared components ---
	tracker := monitor.NewTracker(cfg.Machine.DownloadDir)

	mgr := client.NewManager(cfg)
	mgr.SetTracker(tracker)

	relay := mgr.Relay()

	dash := dashboard.NewServer(mgr, cfg, tracker, relay)

	// --- Signal handling ---
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// --- Start manager (SSE listener + health checks + initial inbox) ---
	if err := mgr.Start(ctx); err != nil {
		log.Fatalf("failed to start manager: %v", err)
	}

	// --- Start Discord bridge (station mode only) ---
	var bot *discord.Bot
	if cfg.IsStation() && cfg.Discord.Enabled && cfg.Discord.Token != "" {
		sseClient := mgr.SSE()
		bot, err = discord.NewBot(cfg, relay, sseClient)
		if err != nil {
			log.Printf("[wraith] failed to create discord bot: %v", err)
		} else {
			if err := bot.Start(); err != nil {
				log.Printf("[wraith] failed to start discord bot: %v", err)
				bot = nil
			}
		}
	}

	// --- Start dashboard HTTP server ---
	dashAddr := fmt.Sprintf("%s:%d", cfg.Web.Host, cfg.Web.Port)
	dashServer := &http.Server{
		Addr:    dashAddr,
		Handler: dash.Handler(),
	}

	go func() {
		log.Printf("[wraith] Mission Control at http://%s", dashAddr)
		if err := dashServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Printf("[wraith] dashboard server error: %v", err)
		}
	}()

	// --- Periodic tracker save (every 5 minutes) ---
	saveTicker := time.NewTicker(5 * time.Minute)
	go func() {
		for {
			select {
			case <-saveTicker.C:
				tracker.Save()
			case <-ctx.Done():
				return
			}
		}
	}()

	// --- Wait for shutdown signal ---
	<-ctx.Done()
	log.Printf("[wraith] shutting down...")

	saveTicker.Stop()

	// Stop discord bot
	if bot != nil {
		bot.Stop()
	}

	// Stop manager (graceful: waits for running agents, saves state)
	mgr.Stop()

	// Shut down dashboard server
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	dashServer.Shutdown(shutdownCtx)

	log.Printf("[wraith] stopped")
}

// runInit generates a wraith.yaml scaffold in the current directory.
func runInit(args []string) {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	project := fs.String("project", "", "project name (default: directory name)")
	relay := fs.String("relay", "http://localhost:8090", "relay server URL")
	machine := fs.String("machine", "", "machine name (default: hostname)")
	fs.Parse(args)

	// Derive project name from directory
	if *project == "" {
		cwd, _ := os.Getwd()
		*project = strings.ToLower(filepath.Base(cwd))
		*project = strings.ReplaceAll(*project, " ", "-")
	}

	// Derive machine name from hostname
	if *machine == "" {
		h, _ := os.Hostname()
		if h == "" {
			h = "localhost"
		}
		*machine = strings.ToLower(h)
	}

	outPath := "wraith.yaml"
	if _, err := os.Stat(outPath); err == nil {
		fmt.Fprintf(os.Stderr, "%s already exists. Remove it first or edit manually.\n", outPath)
		os.Exit(1)
	}

	cwd, _ := os.Getwd()

	config := fmt.Sprintf(`# WRAI.TH Fleet Manager Configuration
# Generated by: wraith init --project %s

mode: station  # "station" (runs relay+dashboard+discord) or "satellite" (manager only)

relay:
  url: %s
  project: %s
  # api_key: ${RELAY_API_KEY}  # uncomment if auth is enabled

machine:
  name: %s
  download_dir: ./data

web:
  host: 0.0.0.0
  port: 8091

# Discord bridge (station mode only)
discord:
  enabled: false
  # token: ${DISCORD_TOKEN}
  # guild_id: "your-guild-id"
  # channels:
  #   engineering: "channel-id"

# Agent definitions
# Each agent runs as a Claude subprocess managed by this machine.
# Agents on other machines are visible but not spawned locally.
agents:
  cto:
    profile_slug: cto
    role: "Technical leader. Owns the backlog, coordinates teams."
    reports_to: ""
    is_executive: true
    work_dir: %s
    machine: %s
    pool: engineering
    model: sonnet
    auto_spawn: true
    max_context_bytes: 16384
    interest_tags: [architecture, planning, coordination]

  # Add more agents:
  # backend:
  #   profile_slug: backend-lead
  #   role: "Backend engineer"
  #   reports_to: cto
  #   work_dir: %s
  #   machine: %s
  #   pool: engineering
  #   model: sonnet
  #   interest_tags: [backend, api, database]

# Team pools (for team: broadcasts)
pools:
  engineering:
    lead: cto
    members: []
    # channel: "discord-channel-id"  # for Discord routing

# SSE tuning
sse:
  reconnect_delay_seconds: 3
  fallback_poll_seconds: 10
  health_check_interval_seconds: 30
`, *project, *relay, *project, *machine, cwd, *machine, cwd, *machine)

	if err := os.WriteFile(outPath, []byte(config), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Created %s for project %q on machine %q\n", outPath, *project, *machine)
	fmt.Printf("  relay: %s\n", *relay)
	fmt.Printf("\nNext steps:\n")
	fmt.Printf("  1. Edit %s — add your agents, set work_dir paths\n", outPath)
	fmt.Printf("  2. Run: wraith\n")
	fmt.Printf("  3. Open Mission Control: http://localhost:8091\n")
}
